---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-application
spec:
  selector:
    matchLabels:
      app: kubernetes
  replicas: 2
  template:
    metadata:
      labels:
        app: kubernetes
    spec:
      containers:
      - name: kubernetes
        image: edez58/kubernetes
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000